#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Programming Seminars  # The title of the book. Will be placed in the left navbar.
author                      : Karl Henrik Fredly  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        :   # A path to the book logo
only_build_toc_files        : true

execute:
    execute_notebooks         : off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
    cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`

launch_buttons:
    binderhub_url             : false

html:
    extra_navbar              : ""  # Will be displayed underneath the left navbar.
    extra_footer              : ""  # Will be displayed underneath the footer.
    google_analytics_id       : ""  # A GA id that can be used to track book views.
    home_page_in_navbar       : true
